### ISSUE TITLE
[Mbed-OS 5.13 OOB] bootloader compatibility issue

### ISSUE THREAD

**Issue by soleilplanet** [ARMmbed/mbed-os-example-cpu-usage#30]
### Description
The example uses default bootloader (v3.4) with NVSTORE support. However, if the device had flashed bootloader 4.x with KVSTORE (e.g. PDMC example 3.x), the example could not run after image flashing.
Suggest to either specify bootloader option in mbed_app.json, or add descriptions on how to deal with such kind of issues in README and official document site.

### Issue request type
[ ] Question  
[X] Enhancement  
[ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1273*

**Comment by evedon** [comment]
What issue did you get when running the example?
In any case, we should update the example to use latest bootloader with KVSTORE support. I don't think it is a valid use case to flash an old bootloader.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
